version: '3'

services:
  nest-api:
    image: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: linkedin
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: linkedin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
