version: '3'

services:
  nest-api:
    image: nest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: dpg-cmggac0l5elc73ft6310-a
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgresql_posts_user
      POSTGRES_PASSWORD: ptvlz0fqyGN6cUJ3hoNbktdrtVfAVt17
      POSTGRES_DB: postgresql_posts
    depends_on:
      - database

  database:
    image: postgres-db
    environment:
      POSTGRES_DB: postgresql_posts
      POSTGRES_USER: postgresql_posts_user
      POSTGRES_PASSWORD: ptvlz0fqyGN6cUJ3hoNbktdrtVfAVt17
